# -*- coding: utf-8 -*-
"""E11 Lab 2/14 - Daksh Rana

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIklMUReIrcy0Nnme-mGrebhLdPCrqkf
"""

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('test.csv')

plt.hist(data['PM25'])
plt.ylabel('Frequency')
plt.xlabel('PM25')
plt.show()

